version: "3.9"  # optional since v1.27.0
services:
  kgs:
    image: wayne900619/kgs:latest
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=kgs
      - PORT=50051
      - KEY_LENGTH=4 # if you want to use in production, change to 6 or more
  
  shorturl:
    restart: always
    image: wayne900619/shorturl:latest
    ports:
      - 8080:8080
    depends_on:
      kgs:
        condition: service_started
      redis:
        condition: service_started
      cassandra:
        condition: service_healthy
    environment:
      - REDIS_HOSTS=redis:6379
      - REDIS_PASSWORD=mysecretpassword
      - CASSANDRA_HOSTS=cassandra:9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_KEYSPACE=shorturl
      - HTTP_PORT=8080
      - KGS_ADDR=kgs:50051

  redis:
    image: redis
    command: redis-server --requirepass $$REDIS_HOST_PASSWORD
    environment:
      - REDIS_HOST_PASSWORD=mysecretpassword

  cassandra:
    image: bitnami/cassandra:latest
    environment:
      - CASSANDRA_HOST=cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=kgs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kgs"]
      interval: 1s
      timeout: 5s
      retries: 5