openapi: "3.0.0"
info:
  title: URL Shortener V1
  version: 1.0.0
  description: URL Shortener using Key Generation Service (KGS)
  contact:
    name: Wayne Chen
    email: wayne900619@gmail.com
servers:
  - url: https://{hostname}
    variables:
      hostname:
        default: localhost
paths:
  /api/v1/urls:
    post:
      operationId: createShortUrl
      requestBody:
        description: needed info to create ShortUrl
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostShortUrl'
      responses:
        '201':
          description: shortUrl and id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortUrl'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{urlId}:
    get:
      operationId: redirectToOriginUrl
      parameters:
        - in: path
          name: urlId
          schema:
            type: string
          required: true
          description: short url id
      responses:
        '302':
          description: redirect to origin url
          headers:
            Location:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PostShortUrl:
      type: object
      required:
        - url
        - expireAt
      properties:
        url:
          type: string
        expireAt:
          type: string
          format: date-time
    ShortUrl:
      type: object
      required:
        - id
        - shortUrl
      properties:
        id:
          type: string
        shortUrl:
          type: string
    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
