// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package ports

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// PostShortUrl defines model for PostShortUrl.
type PostShortUrl struct {
	ExpireAt time.Time `json:"expireAt"`
	Url      string    `json:"url"`
}

// ShortUrl defines model for ShortUrl.
type ShortUrl struct {
	Id       string `json:"id"`
	ShortUrl string `json:"shortUrl"`
}

// CreateShortUrlJSONBody defines parameters for CreateShortUrl.
type CreateShortUrlJSONBody PostShortUrl

// CreateShortUrlJSONRequestBody defines body for CreateShortUrl for application/json ContentType.
type CreateShortUrlJSONRequestBody CreateShortUrlJSONBody
